using Mapping_Tools.Annotations;
using Mapping_Tools.Classes.SystemTools;
using Newtonsoft.Json;
using System.ComponentModel;
using System.Linq;
using System.Reflection;

namespace Mapping_Tools.Classes.SnappingTools.DataStructure.RelevantObjectGenerators {
    public class GeneratorSettings : BindableBase {
        [JsonIgnore]
        [CanBeNull]
        public RelevantObjectsGenerator Generator { get; set; }

        public GeneratorSettings() {
            _relevancyRatio = 0.8;
            GeneratesInheritable = true;
        }

        public GeneratorSettings(RelevantObjectsGenerator generator) {
            Generator = generator;

            _relevancyRatio = 0.8;
            GeneratesInheritable = true;
        }

        private bool _isActive;
        [Description("Active generators can generate virtual objects from hit objects or other virtual objects.")]
        public bool IsActive
        {
            get => _isActive;
            set => Set(ref _isActive, value);
        }

        private bool _isSequential;
        [Description("Sequential generators will only take sequential objects as input.")]
        public bool IsSequential {
            get => _isSequential;
            set => Set(ref _isSequential, value);
        }

        private bool _isDeep;
        [Description("Deep generators can take objects as input not only from the previous layer, but all previous layers.")]
        public bool IsDeep {
            get => _isDeep;
            set => Set(ref _isDeep, value);
        }

        private double _relevancyRatio;
        [Description("The multiplier for the relevancy of virtual objects generated by this generator.")]
        public double RelevancyRatio {
            get => _relevancyRatio;
            set => Set(ref _relevancyRatio, value);
        }

        private bool _generatesInheritable;
        [Description("Specifies whether virtual objects generated by this generator are inheritable.")]
        public bool GeneratesInheritable {
            get => _generatesInheritable;
            set => Set(ref _generatesInheritable, value);
        }

        public void CopyTo(GeneratorSettings other) {
            var otherProperties = other.GetType().GetProperties();
            foreach (var prop in GetType().GetProperties()) {
                if (!prop.CanWrite || !prop.CanRead) continue;
                if (!otherProperties.Contains(prop)) continue;
                if (prop.GetCustomAttribute(typeof(JsonIgnoreAttribute)) != null) continue;
                try { prop.SetValue(other, prop.GetValue(this)); } catch {
                    // ignored
                }
            }
        }

        public object Clone() {
            return MemberwiseClone();
        }
    }
}