<Project>
  <PropertyGroup Condition="'$(IsTestProject)' != 'true'
                            and '$(MSBuildProjectName)' != 'Mapping_Tools'
                            and '$(MSBuildProjectName)' != 'Mapping_Tools_Tests'">
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <WarningsAsErrors>$(WarningsAsErrors);CS1591</WarningsAsErrors>
  </PropertyGroup>
</Project>
