<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Mapping_Tools.Application\Mapping_Tools.Application.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="EditorReader">
      <HintPath>..\lib\EditorReader.dll</HintPath>
      <Private>true</Private>
    </Reference>
    <Reference Include="NonInvasiveKeyboardHookLibrary.Core">
      <HintPath>..\lib\NonInvasiveKeyboardHookLibrary.Core.dll</HintPath>
      <Private>true</Private>
    </Reference>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Newtonsoft.Json" Version="13.0.2" />
  </ItemGroup>

</Project>
