using Mapping_Tools_Core.Audio.Exporting;
using Mapping_Tools_Core.Audio.SampleGeneration.Decorators;
using NAudio.Wave;

namespace Mapping_Tools_Core.Audio.SampleGeneration {
    /// <summary>
    /// Sample generator that generates wave audio.
    /// Expected to work with <see cref="IAudioSampleExporter"/>.
    /// </summary>
    public interface IAudioSampleGenerator : ISampleGenerator, IPreloadableGenerator {
        /// <summary>
        /// Generates a new <see cref="ISampleProvider"/> with the sound of this generator.
        /// 
        /// <remarks>
        /// This <see cref="ISampleProvider"/> instance should be discarded before a new
        /// <see cref="ISampleProvider"/> is generated by this generator.
        /// </remarks>
        /// </summary>
        /// <returns></returns>
        ISampleProvider GetSampleProvider();

        /// <summary>
        /// Gets the factor of changes to the amplitude of the audio.
        /// 1.0 is default, 0.5 is half amplitude, etc.
        /// </summary>
        /// <returns></returns>
        double GetAmplitudeFactor();
    }
}