using NAudio.Wave;

namespace Mapping_Tools_Core.Audio.SampleGeneration {
    public interface IAudioSampleGenerator : ISampleGenerator {
        /// <summary>
        /// Generates a new <see cref="ISampleProvider"/> with the sound of this generator.
        /// 
        /// <remarks>
        /// This <see cref="ISampleProvider"/> instance should be discarded before a new
        /// <see cref="ISampleProvider"/> is generated by this generator.
        /// </remarks>
        /// </summary>
        /// <returns></returns>
        ISampleProvider GetSampleProvider();

        /// <summary>
        /// Do the necessary pre-loading and caching to make <see cref="GetSampleProvider"/> fast.
        /// </summary>
        void PreLoadSample();
    }
}