using NAudio.Wave;

namespace Mapping_Tools_Core.Audio.SampleSoundGeneration {
    /// <summary>
    /// Serves as a reusable source of identical <see cref="ISampleProvider"/>.
    /// </summary>
    public interface ISampleSoundGenerator {
        /// <summary>
        /// Generates a new <see cref="ISampleProvider"/> with the sound of this generator.
        /// 
        /// <remarks>
        /// This <see cref="ISampleProvider"/> instance should be discarded before a new
        /// <see cref="ISampleProvider"/> is generated by this generator.
        /// </remarks>
        /// </summary>
        /// <returns></returns>
        ISampleProvider GetSampleProvider();

        /// <summary>
        /// Whether this generator makes any sound at all.
        /// </summary>
        /// <returns></returns>
        bool IsBlank();

        /// <summary>
        /// Gets the <see cref="WaveFormat"/> of the audio source.
        /// </summary>
        /// <returns></returns>
        WaveFormat GetSourceWaveFormat();
    }
}