using System;
using Mapping_Tools.Core.Classes.SystemTools;
using Mapping_Tools.Core.Classes.Tools.SnappingTools.DataStructure.RelevantObject;

namespace Mapping_Tools.Core.Classes.Tools.SnappingTools.DataStructure.RelevantObjectGenerators.GeneratorInputSelection;

/// <summary>Describes the conditions an input object must satisfy for a generator.</summary>
public sealed class SelectionPredicate : BindableBase, IEquatable<SelectionPredicate>, ICloneable
{
    private bool _needSelected;
    private bool _needLocked;
    private bool _needGeneratedByThis;
    private bool _needGeneratedNotByThis;
    private double _minRelevancy;

    /// <summary>Gets or sets whether the input must be selected.</summary>
    public bool NeedSelected { get => _needSelected; set => Set(ref _needSelected, value); }

    /// <summary>Gets or sets whether the input must be locked.</summary>
    public bool NeedLocked { get => _needLocked; set => Set(ref _needLocked, value); }

    /// <summary>Gets or sets whether the input must have been generated by this generator.</summary>
    public bool NeedGeneratedByThis { get => _needGeneratedByThis; set => Set(ref _needGeneratedByThis, value); }

    /// <summary>Gets or sets whether the input must not have been generated by this generator.</summary>
    public bool NeedGeneratedNotByThis { get => _needGeneratedNotByThis; set => Set(ref _needGeneratedNotByThis, value); }

    /// <summary>Gets or sets the minimum inclusive relevance required from the input.</summary>
    public double MinRelevancy { get => _minRelevancy; set => Set(ref _minRelevancy, value); }

    /// <summary>Checks this predicate against an object and its producing generator.</summary>
    /// <param name="relevantObject">The candidate object.</param>
    /// <param name="generator">The generator evaluating the candidate.</param>
    /// <returns><see langword="true"/> when every configured condition passes.</returns>
    public bool Check(IRelevantObject relevantObject, RelevantObjectsGenerator generator)
    {
        if (NeedSelected && !relevantObject.IsSelected) return false;
        if (NeedLocked && !relevantObject.IsLocked) return false;
        if (NeedGeneratedByThis && (relevantObject.Generator is null || relevantObject.Generator != generator)) return false;
        if (NeedGeneratedNotByThis && relevantObject.Generator is not null && relevantObject.Generator == generator) return false;
        return !(relevantObject.Relevancy < MinRelevancy);
    }

    /// <inheritdoc/>
    public override string ToString() => $"NeedSelected: {NeedSelected}, NeedLocked: {NeedLocked}, NeedGeneratedByThis: {NeedGeneratedByThis}, NeedGeneratedNotByThis: {NeedGeneratedNotByThis}, MinRelevancy: {MinRelevancy}";

    /// <inheritdoc/>
    public object Clone() => MemberwiseClone();

    /// <inheritdoc/>
    public bool Equals(SelectionPredicate? other)
    {
        if (other is null) return false;
        if (ReferenceEquals(this, other)) return true;
        return _needSelected == other._needSelected &&
               _needLocked == other._needLocked &&
               _needGeneratedByThis == other._needGeneratedByThis &&
               _needGeneratedNotByThis == other._needGeneratedNotByThis &&
               _minRelevancy.Equals(other._minRelevancy);
    }

    /// <inheritdoc/>
    public override bool Equals(object? obj) => obj is SelectionPredicate predicate && Equals(predicate);

    /// <inheritdoc/>
    public override int GetHashCode()
    {
        unchecked
        {
            int hashCode = _needSelected.GetHashCode();
            hashCode = hashCode * 397 ^ _needLocked.GetHashCode();
            hashCode = hashCode * 397 ^ _needGeneratedByThis.GetHashCode();
            hashCode = hashCode * 397 ^ _needGeneratedNotByThis.GetHashCode();
            hashCode = hashCode * 397 ^ _minRelevancy.GetHashCode();
            return hashCode;
        }
    }
}
