using System;
using Mapping_Tools.Core.Classes.Tools.SnappingTools.DataStructure.RelevantObject;

namespace Mapping_Tools.Core.Classes.Tools.SnappingTools.DataStructure.RelevantObjectGenerators.GeneratorInputSelection;

/// <summary>Describes the conditions an input object must satisfy for a generator.</summary>
public sealed class SelectionPredicate : IEquatable<SelectionPredicate>, ICloneable
{
    /// <summary>Gets or sets whether the input must be selected.</summary>
    public bool NeedSelected { get; set; }

    /// <summary>Gets or sets whether the input must be locked.</summary>
    public bool NeedLocked { get; set; }

    /// <summary>Gets or sets whether the input must have been generated by this generator.</summary>
    public bool NeedGeneratedByThis { get; set; }

    /// <summary>Gets or sets whether the input must not have been generated by this generator.</summary>
    public bool NeedGeneratedNotByThis { get; set; }

    /// <summary>Gets or sets the minimum inclusive relevance required from the input.</summary>
    public double MinRelevancy { get; set; }

    /// <summary>Checks this predicate against an object and its producing generator.</summary>
    /// <param name="relevantObject">The candidate object.</param>
    /// <param name="generator">The generator evaluating the candidate.</param>
    /// <returns><see langword="true"/> when every configured condition passes.</returns>
    public bool Check(IRelevantObject relevantObject, RelevantObjectsGenerator generator)
    {
        if (NeedSelected && !relevantObject.IsSelected) return false;
        if (NeedLocked && !relevantObject.IsLocked) return false;
        if (NeedGeneratedByThis && (relevantObject.Generator is null || relevantObject.Generator != generator)) return false;
        if (NeedGeneratedNotByThis && relevantObject.Generator is not null && relevantObject.Generator == generator) return false;
        return !(relevantObject.Relevancy < MinRelevancy);
    }

    /// <inheritdoc/>
    public override string ToString() => $"NeedSelected: {NeedSelected}, NeedLocked: {NeedLocked}, NeedGeneratedByThis: {NeedGeneratedByThis}, NeedGeneratedNotByThis: {NeedGeneratedNotByThis}, MinRelevancy: {MinRelevancy}";

    /// <inheritdoc/>
    public object Clone() => MemberwiseClone();

    /// <inheritdoc/>
    public bool Equals(SelectionPredicate? other)
    {
        if (other is null) return false;
        if (ReferenceEquals(this, other)) return true;
        return NeedSelected == other.NeedSelected &&
               NeedLocked == other.NeedLocked &&
               NeedGeneratedByThis == other.NeedGeneratedByThis &&
               NeedGeneratedNotByThis == other.NeedGeneratedNotByThis &&
               MinRelevancy.Equals(other.MinRelevancy);
    }

    /// <inheritdoc/>
    public override bool Equals(object? obj) => obj is SelectionPredicate predicate && Equals(predicate);

    /// <inheritdoc/>
    public override int GetHashCode()
    {
        unchecked
        {
            int hashCode = NeedSelected.GetHashCode();
            hashCode = hashCode * 397 ^ NeedLocked.GetHashCode();
            hashCode = hashCode * 397 ^ NeedGeneratedByThis.GetHashCode();
            hashCode = hashCode * 397 ^ NeedGeneratedNotByThis.GetHashCode();
            hashCode = hashCode * 397 ^ MinRelevancy.GetHashCode();
            return hashCode;
        }
    }
}
