using System;
using System.ComponentModel;
using System.Linq;
using System.Reflection;
using Mapping_Tools.Annotations;
using Mapping_Tools.Classes.SystemTools;
using Mapping_Tools.Classes.Tools.SnappingTools.DataStructure.RelevantObjectGenerators.GeneratorInputSelection;
using Newtonsoft.Json;

namespace Mapping_Tools.Classes.Tools.SnappingTools.DataStructure.RelevantObjectGenerators {
    public class GeneratorSettings : BindableBase, ICloneable {
        [JsonIgnore]
        [CanBeNull]
        public RelevantObjectsGenerator Generator { get; set; }

        public GeneratorSettings() {
            relevancyRatio = 0.4;
            generatesInheritable = true;
            inputPredicate = new SelectionPredicateCollection();
        }

        public GeneratorSettings(RelevantObjectsGenerator generator) {
            Generator = generator;

            relevancyRatio = 0.4;
            generatesInheritable = true;
            inputPredicate = new SelectionPredicateCollection();
        }

        private bool isActive;
        [DisplayName("Active")]
        [Description("Active generators can generate virtual objects from hit objects or other virtual objects.")]
        public bool IsActive
        {
            get => isActive;
            set => Set(ref isActive, value);
        }

        private bool isSequential;
        [DisplayName("Sequential")]
        [Description("Sequential generators will only take sequential objects as input.")]
        public bool IsSequential {
            get => isSequential;
            set => Set(ref isSequential, value);
        }

        private bool isDeep;
        [DisplayName("Deep")]
        [Description("Deep generators can take objects as input not only from the previous layer, but all previous layers.")]
        public bool IsDeep {
            get => isDeep;
            set => Set(ref isDeep, value);
        }

        private double relevancyRatio;
        [DisplayName("Relevancy Ratio")]
        [Description("The multiplier for the relevancy of virtual objects generated by this generator.")]
        public double RelevancyRatio {
            get => relevancyRatio;
            set => Set(ref relevancyRatio, value);
        }

        private bool generatesInheritable;
        [DisplayName("Generates Inheritable")]
        [Description("Specifies whether virtual objects generated by this generator are inheritable.")]
        public bool GeneratesInheritable {
            get => generatesInheritable;
            set => Set(ref generatesInheritable, value);
        }

        private SelectionPredicateCollection inputPredicate;
        [DisplayName("Input Selection")]
        [Description("Specifies extra rules that virtual objects need to obey to be used by this generator. Only one of the predicates has to be met by any virtual object.")]
        public SelectionPredicateCollection InputPredicate {
            get => inputPredicate;
            set => Set(ref inputPredicate, value);
        }

        public void CopyTo(GeneratorSettings other) {
            var otherPropertyNames = other.GetType().GetProperties().Select(o => o.Name).ToArray();
            foreach (var prop in GetType().GetProperties()) {
                if (!prop.CanWrite || !prop.CanRead) continue;
                if (!otherPropertyNames.Contains(prop.Name)) continue;
                if (prop.GetCustomAttribute(typeof(JsonIgnoreAttribute)) != null) continue;
                try { prop.SetValue(other, prop.GetValue(this)); } catch (Exception ex) {
                    Console.WriteLine(ex.Message + ex.StackTrace);
                }
            }
        }

        public virtual object Clone() {
            return new GeneratorSettings {Generator = Generator, IsActive = IsActive, IsSequential = IsSequential, IsDeep = IsDeep, 
                RelevancyRatio = RelevancyRatio, GeneratesInheritable = GeneratesInheritable,
                InputPredicate = (SelectionPredicateCollection)InputPredicate.Clone()};
        }
    }
}